/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
// char *strncpy(char *dest, const char *src, size_t n);
// void __noreturn exit(int status);
// __int64 __fastcall _read_chk(_QWORD, char *nptr, int n23, int n24); idb
// int puts(const char *s);
// int fclose(FILE *stream);
// int printf(const char *format, ...);
// int snprintf(char *s, size_t maxlen, const char *format, ...);
// void *memset(void *s, int c, size_t n);
// unsigned int alarm(unsigned int seconds);
// int close(int fd);
// ssize_t read(int fd, void *buf, size_t nbytes);
// void srand(unsigned int seed);
// __int64 atoll(const char *nptr);
// int strcmp(const char *s1, const char *s2);
// int getchar(void);
// __sighandler_t signal(int sig, __sighandler_t handler);
// int fprintf(FILE *stream, const char *format, ...);
// int prctl(int option, ...);
// time_t time(time_t *timer);
// void *realloc(void *ptr, size_t size);
// __int64 __fastcall _printf_chk(__int64, const char *);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int open(const char *file, int oflag, ...);
// FILE *fopen(const char *filename, const char *modes);
// int sprintf(char *s, const char *format, ...);
// void __noreturn exit(int status);
// size_t fwrite(const void *ptr, size_t size, size_t n, FILE *s);
// int __fastcall _cxa_finalize(void *);
// int rand(void);
__int64 (**sub_E00())(void);
__int64 sub_E40();
__int64 (**sub_E90())(void);
__int64 sub_ED0(); // weak
unsigned __int64 fn_install_seccomp_filter_F00();
void __noreturn fn_alarm_timeout_handler();
unsigned int fn_game_init_FFC();
__int64 fn_read_number_1134();
__int64 __fastcall fn_printf_msg_11C0(const char *a1, int a2);
unsigned __int64 __fastcall fn_read_string_11FF(char *title, int n0x18);
int fn_pantry_list_ingredient_15C0();
__int64 fn_recipe_print_menu_16A4();
__int64 __fastcall fn_recipe_attach_ingredient_1721(Recipe *a1, Ingredient *a2);
unsigned __int64 fn_add_new_recipe_17DC();
int __fastcall fn_show_recipe_1A9B(int a1);
unsigned __int64 fn_remove_recipe_1B90();
unsigned __int64 fn_recipe_1CA9();
int fn_chef_info_1D5A();
__int64 fn_main_menu_print_1DF4();
struct Recipe *fn_init_default_player_pantry_and_recipes_1E95();
time_t fn_shop_init_inventory_2149();
unsigned __int64 fn_cook_2259();
int fn_cooked_food_list_print_25E1();
__int64 fn_menu_shop_26C7();
int fn_sell_2744();
struct Ingredient *fn_make_2895();
int fn_eat_2A12();
int fn_assignment_2B62();
struct Ingredient *fn_shop_list_and_autorestock_2DCA();
int fn_buy_2F40();
unsigned __int64 fn_shop_30E3();
_BYTE *fn_player_init_profile_316C();
void __fastcall __noreturn main(int a1, char **a2, char **a3);
__int64 __fastcall fn_patch_seccomp_labels_32BA(_BYTE *buf, _BYTE *p_g_dataSeccomp_36E0, unsigned __int64 n0x19); // idb
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void fini(void); // idb
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __fastcall __cxa_finalize(void *);
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 _gmon_start__(void); weak
// __int64 Jv_RegisterClasses(void); weak

//-------------------------------------------------------------------------
// Data declarations

// extern _UNKNOWN _isoc99_scanf; weak
_UNKNOWN fn_pantry_add_or_update_ingredient_1276;
_UNKNOWN fn_shop_add_or_update_ingredient_141B;
_UNKNOWN g_dataSeccomp_36E0; // weak
const char s_ = '\xF0'; // idb
__int64 (__fastcall *off_204CF0[2])() = { &sub_ED0, &sub_E90 }; // weak
__int64 (__fastcall *off_204CF8)() = &sub_E90; // weak
_UNKNOWN unk_204D00; // weak
void *off_205008 = &off_205008; // idb
_UNKNOWN unk_205010; // weak
_UNKNOWN unk_205017; // weak
FILE *stdout; // idb
FILE *stdin; // idb
FILE *stderr; // idb
char byte_205048; // weak
char *g_tmpMsgBuf_205050; // idb
FILE *g_flagFile_205058; // idb
struct CookedFood *g_foodListHead_205060;
uint32_t g_shopRestockEpoch_205068;
uint32_t g_pantryCount_20506C;
uint32_t g_shopCount_205070;
struct Ingredient *g_shopSlots_205080;
char g_playerName_2050A0[8];
int g_playerLevel_2050A8;
unsigned __int64 g_playerXPBar_2050B0;
unsigned __int64 g_playerPower_2050B8;
unsigned __int64 g_playerMoney_2050C0;
struct Ingredient *g_pantrySlots_2050C8;
Recipe *g_recipeListHead_2050D0;
unsigned __int8 g_heapMagicKey_2050D8[8];


//----- (0000000000000CA8) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**__gmon_start_)(void); // rax

  __gmon_start_ = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return __gmon_start_;
}
// 206498: using guessed type __int64 _gmon_start__(void);

//----- (0000000000000DD0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*rtld_fini)(void))
{
  __int64 stack_end__1; // rax
  int argc; // esi
  __int64 stack_end_; // [rsp-8h] [rbp-8h] BYREF
  char *ubp_av_; // [rsp+0h] [rbp+0h] BYREF

  argc = stack_end_;
  stack_end_ = stack_end__1;
  _libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    argc,
    &ubp_av_,
    (void (*)(void))init,
    fini,
    rtld_fini,
    &stack_end_);
  __halt();
}
// DD6: positive sp value 8 has been found
// DDD: variable 'v3' is possibly undefined

//----- (0000000000000E00) ----------------------------------------------------
__int64 (**sub_E00())(void)
{
  __int64 (**p__ITM_deregisterTMCloneTable)(void); // rax

  p__ITM_deregisterTMCloneTable = (__int64 (**)(void))(&unk_205017 - &unk_205010);
  if ( (unsigned __int64)(&unk_205017 - &unk_205010) > 0xE )
  {
    p__ITM_deregisterTMCloneTable = &ITM_deregisterTMCloneTable;
    if ( &ITM_deregisterTMCloneTable )
      return (__int64 (**)(void))ITM_deregisterTMCloneTable();
  }
  return p__ITM_deregisterTMCloneTable;
}
// 206490: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (0000000000000E40) ----------------------------------------------------
__int64 sub_E40()
{
  return 0;
}

//----- (0000000000000E90) ----------------------------------------------------
__int64 (**sub_E90())(void)
{
  __int64 (**result)(void); // rax

  if ( !byte_205048 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_205008);
    result = sub_E00();
    byte_205048 = 1;
  }
  return result;
}
// 205048: using guessed type char byte_205048;

//----- (0000000000000ED0) ----------------------------------------------------
__int64 sub_ED0()
{
  if ( unk_204D00 && &Jv_RegisterClasses )
    Jv_RegisterClasses();
  return sub_E40();
}
// ED0: using guessed type __int64 sub_ED0();
// 2064A0: using guessed type __int64 Jv_RegisterClasses(void);

//----- (0000000000000F00) ----------------------------------------------------
unsigned __int64 fn_install_seccomp_filter_F00()
{
  __int64 v0; // r9
  __int64 v2; // [rsp+0h] [rbp-10F0h] BYREF
  _BYTE p_g_dataSeccomp_36E0[208]; // [rsp+10h] [rbp-10E0h] BYREF
  _BYTE buf[4104]; // [rsp+E0h] [rbp-1010h] BYREF
  unsigned __int64 v5; // [rsp+10E8h] [rbp-8h]

  v5 = __readfsqword(0x28u);
  memset(buf, 0, sizeof(buf));
  qmemcpy(p_g_dataSeccomp_36E0, &g_dataSeccomp_36E0, 0xC8u);
  fn_patch_seccomp_labels_32BA((__int64)buf, (__int64)p_g_dataSeccomp_36E0, 0x19u);
  LOWORD(v2) = 25;
  prctl(38, 1, 0, 0, 0, v0, v2, p_g_dataSeccomp_36E0);
  prctl(22, 2, &v2);
  return __readfsqword(0x28u) ^ v5;
}
// FA1: variable 'v0' is possibly undefined

//----- (0000000000000FDB) ----------------------------------------------------
void __noreturn fn_alarm_timeout_handler()
{
  puts("Timeout");
  exit(1);
}

//----- (0000000000000FFC) ----------------------------------------------------
unsigned int fn_game_init_FFC()
{
  unsigned int seed; // eax
  int fd; // [rsp+Ch] [rbp-4h]

  setvbuf(stdin, 0, 2, 0);
  setvbuf(stdout, 0, 2, 0);
  setvbuf(stderr, 0, 2, 0);
  seed = time(0);
  srand(seed);
  g_flagFile_205058 = fopen("/home/food_store/flag", "r");
  if ( !g_flagFile_205058 )
  {
    puts("Open failed !");
    exit(-2);
  }
  g_tmpMsgBuf_205050 = (char *)realloc(0, 0x80u);
  fd = open("/dev/urandom", 0);
  if ( fd < 0 )
  {
    puts("error");
    exit(-1);
  }
  read(fd, g_heapMagicKey_2050D8, 8u);
  close(fd);
  signal(14, (__sighandler_t)fn_alarm_timeout_handler);
  return alarm(0x3Cu);
}

//----- (0000000000001134) ----------------------------------------------------
__int64 fn_read_number_1134()
{
  char nptr[24]; // [rsp+10h] [rbp-20h] BYREF
  unsigned __int64 v2; // [rsp+28h] [rbp-8h]

  v2 = __readfsqword(0x28u);
  if ( (int)_read_chk(0, nptr, 23, 24) <= 0 )
  {
    puts("Error");
    exit(-1);
  }
  return atoll(nptr);
}

//----- (00000000000011C0) ----------------------------------------------------
__int64 __fastcall fn_printf_msg_11C0(const char *a1, int a2)
{
  __int64 result; // rax

  result = _printf_chk(1, "%s");
  if ( a2 )
    exit(-1);
  return result;
}

//----- (00000000000011FF) ----------------------------------------------------
unsigned __int64 __fastcall fn_read_string_11FF(char *title, int n0x18)
{
  unsigned __int64 n10; // rax
  int chk; // [rsp+1Ch] [rbp-4h]

  chk = _read_chk(0, title, n0x18, n0x18);
  if ( chk <= 0 )
  {
    puts("read error");
    exit(1);
  }
  n10 = (unsigned __int8)title[chk - 1];
  if ( (_BYTE)n10 == 10 )
  {
    n10 = (unsigned __int64)&title[chk - 1];
    *(_BYTE *)n10 = 0;
  }
  return n10;
}

//----- (0000000000001276) ----------------------------------------------------
struct Ingredient *__fastcall fn_pantry_add_or_update_ingredient_1276(
        const char *s2,
        uint32_t quantity,
        uint32_t price)
{
  struct Ingredient *g_pantrySlots_2050C8; // rax
  int i; // [rsp+14h] [rbp-Ch]
  int j; // [rsp+14h] [rbp-Ch]
  Ingredient *new_ing; // [rsp+18h] [rbp-8h]

  g_pantrySlots_2050C8 = g_pantrySlots_2050C8;
  if ( g_pantrySlots_2050C8 )
  {
    for ( i = 0; i <= 9; ++i )
    {
      if ( *(_QWORD *)&g_pantrySlots_2050C8->name[8 * i]
        && !strcmp(*(const char **)&g_pantrySlots_2050C8->name[8 * i], s2) )
      {
        g_pantrySlots_2050C8 = *(struct Ingredient **)&g_pantrySlots_2050C8->name[8 * i];
        g_pantrySlots_2050C8->quantity += quantity;
        return g_pantrySlots_2050C8;
      }
    }
    for ( j = 0; ; ++j )
    {
      if ( j > 9 )
        return (struct Ingredient *)fn_printf_msg_11C0("Too many ingredient", 0);
      if ( !*(_QWORD *)&g_pantrySlots_2050C8->name[8 * j] )
        break;
    }
    new_ing = (Ingredient *)realloc(0, 0x28u);
    if ( !new_ing )
      fn_printf_msg_11C0("Allocate failed !", 1);
    strncpy(new_ing->name, s2, 0x1Fu);
    new_ing->price = price;
    new_ing->quantity = quantity;
    *(_QWORD *)&g_pantrySlots_2050C8->name[8 * j] = new_ing;
    return (struct Ingredient *)++g_pantryCount_20506C;
  }
  return g_pantrySlots_2050C8;
}

//----- (000000000000141B) ----------------------------------------------------
struct Ingredient *__fastcall fn_shop_add_or_update_ingredient_141B(const char *s2, uint32_t quantity, uint32_t price)
{
  struct Ingredient *g_pantrySlots_2050C8; // rax
  int i; // [rsp+14h] [rbp-Ch]
  int j; // [rsp+14h] [rbp-Ch]
  Ingredient *new_ing; // [rsp+18h] [rbp-8h]

  g_pantrySlots_2050C8 = g_pantrySlots_2050C8;
  if ( g_pantrySlots_2050C8 )
  {
    for ( i = 0; i <= 9; ++i )
    {
      if ( *(_QWORD *)&g_shopSlots_205080->name[8 * i] && !strcmp(*(const char **)&g_shopSlots_205080->name[8 * i], s2) )
      {
        g_pantrySlots_2050C8 = *(struct Ingredient **)&g_shopSlots_205080->name[8 * i];
        g_pantrySlots_2050C8->quantity += quantity;
        return g_pantrySlots_2050C8;
      }
    }
    for ( j = 0; ; ++j )
    {
      if ( j > 9 )
        return (struct Ingredient *)fn_printf_msg_11C0("Too many ingredient", 0);
      if ( !*(_QWORD *)&g_shopSlots_205080->name[8 * j] )
        break;
    }
    new_ing = (Ingredient *)realloc(0, 0x28u);
    if ( !new_ing )
      fn_printf_msg_11C0("Allocate failed !", 1);
    strncpy(new_ing->name, s2, 0x1Fu);
    new_ing->price = price;
    new_ing->quantity = quantity;
    *(_QWORD *)&g_shopSlots_205080->name[8 * j] = new_ing;
    return (struct Ingredient *)++g_shopCount_205070;
  }
  return g_pantrySlots_2050C8;
}

//----- (00000000000015C0) ----------------------------------------------------
int fn_pantry_list_ingredient_15C0()
{
  int g_pantrySlots_2050C8; // eax
  int i; // [rsp+Ch] [rbp-4h]

  g_pantrySlots_2050C8 = (int)g_pantrySlots_2050C8;
  if ( g_pantrySlots_2050C8 )
  {
    puts(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
    for ( i = 0; i <= 9; ++i )
    {
      if ( *(_QWORD *)&g_pantrySlots_2050C8->name[8 * i] )
        _printf_chk(1, "No.%d\n  Ingredient : %s\n  Quantity : %u\n  Price : %u\n");
    }
    return puts(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
  }
  return g_pantrySlots_2050C8;
}

//----- (00000000000016A4) ----------------------------------------------------
__int64 fn_recipe_print_menu_16A4()
{
  puts("$$$$$$$$$$$$$$$$$$$$$$$$$$");
  puts("          Recipe          ");
  puts("$$$$$$$$$$$$$$$$$$$$$$$$$$");
  puts("$   1. Add new recipe    $");
  puts("$   2. Remove recipe     $");
  puts("$   3. Show recipe       $");
  puts("$   4. Return            $");
  puts("$$$$$$$$$$$$$$$$$$$$$$$$$$");
  return _printf_chk(1, "Your choice: ");
}

//----- (0000000000001721) ----------------------------------------------------
__int64 __fastcall fn_recipe_attach_ingredient_1721(Recipe *a1, Ingredient *a2)
{
  int i; // [rsp+1Ch] [rbp-4h]

  memset(g_tmpMsgBuf_205050, 0, 0x80u);
  for ( i = 0; i <= 12; ++i )
  {
    if ( !a1->ingredients[i] )
    {
      a1->ingredients[i] = a2;
      return 1;
    }
  }
  snprintf(g_tmpMsgBuf_205050, 0x7Fu, "Can not add more ingredient to %s", a1->title);
  fn_printf_msg_11C0(g_tmpMsgBuf_205050, 0);
  return 0;
}

//----- (00000000000017DC) ----------------------------------------------------
unsigned __int64 fn_add_new_recipe_17DC()
{
  int v1; // [rsp+4h] [rbp-7Ch]
  int i; // [rsp+8h] [rbp-78h]
  int j; // [rsp+Ch] [rbp-74h]
  Recipe *new_rec; // [rsp+10h] [rbp-70h]
  Recipe *cur; // [rsp+18h] [rbp-68h]
  size_t idx; // [rsp+20h] [rbp-60h]
  __int64 add_more; // [rsp+28h] [rbp-58h]
  char s[32]; // [rsp+30h] [rbp-50h] BYREF
  char s_1[40]; // [rsp+50h] [rbp-30h] BYREF
  unsigned __int64 v10; // [rsp+78h] [rbp-8h]

  v10 = __readfsqword(0x28u);
  cur = 0;
  idx = 0;
  add_more = 0;
  v1 = 0;
  memset(s, 0, sizeof(s));
  memset(s_1, 0, 0x20u);
  new_rec = (Recipe *)realloc(0, 0x88u);
  if ( !new_rec )
    fn_printf_msg_11C0("Allocate Error !", 1);
  for ( i = 0; i <= 7; ++i )
  {
    s[i] = *((_BYTE *)&new_rec + i);
    sprintf(&s_1[2 * i], "%02X", (unsigned __int8)s[i] ^ g_heapMagicKey_2050D8[i]);
  }
  for ( j = 0; j <= 12; ++j )
    new_rec->ingredients[j] = 0;
  _printf_chk(1, "Magic : %s\n");
  _printf_chk(1, "Title :");
  _isoc99_scanf("%23s", new_rec);
  getchar();
  fn_pantry_list_ingredient_15C0();
  do
  {
    _printf_chk(1, "Choose ingredient :");
    idx = fn_read_number_1134();
    if ( g_pantryCount_20506C <= idx )
    {
      fn_printf_msg_11C0("Out of bound\n", 1);
    }
    else if ( *(_QWORD *)&g_pantrySlots_2050C8->name[8 * idx] )
    {
      v1 = fn_recipe_attach_ingredient_1721(new_rec, *(_QWORD *)&g_pantrySlots_2050C8->name[8 * idx]);
    }
    if ( !v1 )
      break;
    _printf_chk(1, "Add more ingredient ? (1/Yes,2/No) : ");
    add_more = fn_read_number_1134();
  }
  while ( add_more == 1 );
  for ( cur = g_recipeListHead_2050D0; cur && cur->next_recipe; cur = cur->next_recipe )
    ;
  if ( g_recipeListHead_2050D0 )
    cur->next_recipe = new_rec;
  else
    g_recipeListHead_2050D0 = new_rec;
  return __readfsqword(0x28u) ^ v10;
}

//----- (0000000000001A9B) ----------------------------------------------------
int __fastcall fn_show_recipe_1A9B(int a1)
{
  int g_recipeListHead_2050D0; // eax
  int i; // [rsp+14h] [rbp-Ch]
  Recipe *cur; // [rsp+18h] [rbp-8h]

  g_recipeListHead_2050D0 = (int)g_recipeListHead_2050D0;
  if ( g_recipeListHead_2050D0 )
  {
    for ( cur = g_recipeListHead_2050D0; cur; cur = cur->next_recipe )
    {
      puts("-------------------------------------------");
      _printf_chk(1, "Title : %s\n");
      if ( a1 )
      {
        puts("Ingredient :");
        for ( i = 0; i <= 12; ++i )
        {
          if ( cur->ingredients[i] )
            _printf_chk(1, "  %s\n");
        }
      }
    }
    return puts("-------------------------------------------");
  }
  return g_recipeListHead_2050D0;
}

//----- (0000000000001B90) ----------------------------------------------------
unsigned __int64 fn_remove_recipe_1B90()
{
  Recipe *cur; // [rsp+10h] [rbp-30h]
  Recipe *prev; // [rsp+18h] [rbp-28h]
  char title[24]; // [rsp+20h] [rbp-20h] BYREF
  unsigned __int64 v4; // [rsp+38h] [rbp-8h]

  v4 = __readfsqword(0x28u);
  prev = 0;
  memset(title, 0, sizeof(title));
  _printf_chk(1, "Title :");
  fn_read_string_11FF(title, 24);
  if ( g_recipeListHead_2050D0 )
  {
    for ( cur = g_recipeListHead_2050D0; cur; cur = cur->next_recipe )
    {
      if ( !strcmp(cur->title, title) )
      {
        if ( prev )
          prev->next_recipe = cur->next_recipe;
        else
          g_recipeListHead_2050D0 = cur->next_recipe;
        realloc(cur, 0);
        return __readfsqword(0x28u) ^ v4;
      }
      prev = cur;
    }
  }
  return __readfsqword(0x28u) ^ v4;
}

//----- (0000000000001CA9) ----------------------------------------------------
unsigned __int64 fn_recipe_1CA9()
{
  unsigned __int64 n2; // rax

  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          fn_recipe_print_menu_16A4();
          n2 = fn_read_number_1134();
          if ( n2 != 2 )
            break;
          if ( (unsigned int)g_playerLevel_2050A8 <= 2 )
            goto LABEL_9;
          fn_remove_recipe_1B90();
        }
        if ( n2 > 2 )
          break;
        if ( n2 != 1 )
          goto LABEL_14;
        if ( (unsigned int)g_playerLevel_2050A8 > 1 )
          fn_add_new_recipe_17DC();
        else
LABEL_9:
          puts("Your level is too low !");
      }
      if ( n2 != 3 )
        break;
      fn_show_recipe_1A9B(1);
    }
    if ( n2 == 4 )
      return n2;
LABEL_14:
    puts("Invalid Choice");
  }
}

//----- (0000000000001D5A) ----------------------------------------------------
int fn_chef_info_1D5A()
{
  puts("*****************************************");
  _printf_chk(1, "  Name : %s\n");
  _printf_chk(1, "  Level : %u\n");
  _printf_chk(1, "  Power : %lu\n");
  _printf_chk(1, "  Money : %lu\n");
  return puts("*****************************************");
}

//----- (0000000000001DF4) ----------------------------------------------------
__int64 fn_main_menu_print_1DF4()
{
  puts("xxxxxxxxxxxxxxxxxxxxxxxxxxx");
  puts(&s_);
  puts("xxxxxxxxxxxxxxxxxxxxxxxxxxx");
  puts("$   1. Recipe             $");
  puts("$   2. Assignment         $");
  puts("$   3. Chef's infomation  $");
  puts("$   4. Shop               $");
  puts("$   5. Cook               $");
  puts("$   6. Eat                $");
  puts("$   7. Exit               $");
  puts("xxxxxxxxxxxxxxxxxxxxxxxxxxx");
  return _printf_chk(1, "Your choice: ");
}

//----- (0000000000001E95) ----------------------------------------------------
struct Recipe *fn_init_default_player_pantry_and_recipes_1E95()
{
  struct Recipe *j_1; // rax
  Recipe *i; // [rsp+0h] [rbp-10h]
  Recipe *j; // [rsp+0h] [rbp-10h]
  Recipe *next_recipe; // [rsp+8h] [rbp-8h]
  Recipe *next_recipe_1; // [rsp+8h] [rbp-8h]

  g_pantrySlots_2050C8 = (struct Ingredient *)realloc(0, 0x50u);
  if ( !g_pantrySlots_2050C8 )
    fn_printf_msg_11C0("Allocate failed !", 1);
  fn_pantry_add_or_update_ingredient_1276("Egg", 3u, 0x28u);
  fn_pantry_add_or_update_ingredient_1276("Pineapple", 0, 0xD9u);
  fn_pantry_add_or_update_ingredient_1276("Flouir", 2u, 0x7Fu);
  fn_pantry_add_or_update_ingredient_1276("Suger", 3u, 0x28u);
  fn_pantry_add_or_update_ingredient_1276("Beef", 2u, 0x190u);
  next_recipe = (Recipe *)realloc(0, 0x88u);
  if ( !next_recipe )
    fn_printf_msg_11C0("Allocate Error !", 1);
  strcpy(next_recipe->title, "Pineapple cake");
  fn_recipe_attach_ingredient_1721(next_recipe, *(_QWORD *)g_pantrySlots_2050C8->name);
  fn_recipe_attach_ingredient_1721(next_recipe, *(_QWORD *)&g_pantrySlots_2050C8->name[8]);
  fn_recipe_attach_ingredient_1721(next_recipe, *(_QWORD *)&g_pantrySlots_2050C8->name[16]);
  fn_recipe_attach_ingredient_1721(next_recipe, *(_QWORD *)&g_pantrySlots_2050C8->name[16]);
  fn_recipe_attach_ingredient_1721(next_recipe, *(_QWORD *)&g_pantrySlots_2050C8->name[24]);
  for ( i = g_recipeListHead_2050D0; i && i->next_recipe; i = i->next_recipe )
    ;
  if ( g_recipeListHead_2050D0 )
    i->next_recipe = next_recipe;
  else
    g_recipeListHead_2050D0 = next_recipe;
  next_recipe_1 = (Recipe *)realloc(0, 0x88u);
  if ( !next_recipe_1 )
    fn_printf_msg_11C0("Allocate Error !", 1);
  strcpy(next_recipe_1->title, "Beef noodles");
  fn_recipe_attach_ingredient_1721(next_recipe_1, *(_QWORD *)&g_pantrySlots_2050C8->name[16]);
  fn_recipe_attach_ingredient_1721(next_recipe_1, *(_QWORD *)&g_pantrySlots_2050C8->price);
  for ( j = g_recipeListHead_2050D0; j && j->next_recipe; j = j->next_recipe )
    ;
  j_1 = j;
  j->next_recipe = next_recipe_1;
  return j_1;
}

//----- (0000000000002149) ----------------------------------------------------
time_t fn_shop_init_inventory_2149()
{
  time_t g_shopRestockEpoch_205068; // rax

  g_shopSlots_205080 = (struct Ingredient *)realloc(0, 0x50u);
  if ( !g_shopSlots_205080 )
    fn_printf_msg_11C0("Allocate failed !", 1);
  fn_shop_add_or_update_ingredient_141B("Egg", 2u, 0x28u);
  fn_shop_add_or_update_ingredient_141B("Pineapple", 0, 0xD9u);
  fn_shop_add_or_update_ingredient_141B("Flouir", 1u, 0x7Fu);
  fn_shop_add_or_update_ingredient_141B("Suger", 1u, 0x28u);
  fn_shop_add_or_update_ingredient_141B("Apple", 1u, 0x50u);
  fn_shop_add_or_update_ingredient_141B("Beef", 1u, 0x190u);
  fn_shop_add_or_update_ingredient_141B("Salt", 1u, 0x1Eu);
  fn_shop_add_or_update_ingredient_141B("Pork", 1u, 0x12Cu);
  fn_shop_add_or_update_ingredient_141B("Scallion", 1u, 0x14u);
  g_shopRestockEpoch_205068 = time(0);
  g_shopRestockEpoch_205068 = g_shopRestockEpoch_205068;
  return g_shopRestockEpoch_205068;
}

//----- (0000000000002259) ----------------------------------------------------
unsigned __int64 fn_cook_2259()
{
  char *g_tmpMsgBuf_205050; // rax
  Ingredient *v1; // rax
  int total_cost; // [rsp+8h] [rbp-48h]
  int i; // [rsp+Ch] [rbp-44h]
  Recipe *s1; // [rsp+10h] [rbp-40h]
  struct CookedFood *last; // [rsp+18h] [rbp-38h]
  CookedFood *dest; // [rsp+28h] [rbp-28h]
  char title[24]; // [rsp+30h] [rbp-20h] BYREF
  unsigned __int64 v9; // [rsp+48h] [rbp-8h]

  v9 = __readfsqword(0x28u);
  total_cost = 0;
  fn_show_recipe_1A9B(0);
  _printf_chk(1, "What do you want to cook :");
  fn_read_string_11FF((__int64)title, 0x18u);
  if ( g_recipeListHead_2050D0 )
  {
    for ( s1 = g_recipeListHead_2050D0; s1; s1 = s1->next_recipe )
    {
      if ( !strcmp(s1->title, title) )
      {
        if ( g_playerPower_2050B8 > 9 )
        {
          g_playerPower_2050B8 -= 10LL;
        }
        else
        {
          g_tmpMsgBuf_205050 = g_tmpMsgBuf_205050;
          *(_QWORD *)g_tmpMsgBuf_205050 = 0x6576616820756F59LL;
          strcpy(g_tmpMsgBuf_205050 + 8, " no power !");
          fn_printf_msg_11C0(g_tmpMsgBuf_205050, 1);
        }
        for ( i = 0; i <= 12; ++i )
        {
          if ( s1->ingredients[i] )
          {
            if ( s1->ingredients[i]->quantity )
            {
              v1 = s1->ingredients[i];
              --v1->quantity;
              total_cost += s1->ingredients[i]->price;
            }
            else
            {
              snprintf(g_tmpMsgBuf_205050, 0x7Fu, "Run out of %s\n", s1->ingredients[i]->name);
              fn_printf_msg_11C0(g_tmpMsgBuf_205050, 1);
            }
          }
        }
        if ( g_playerXPBar_2050B0 + 60 <= 0x63 )
        {
          g_playerXPBar_2050B0 += 60LL;
        }
        else
        {
          ++g_playerLevel_2050A8;
          g_playerXPBar_2050B0 -= 40LL;
        }
        dest = (CookedFood *)realloc(0, 0x38u);
        dest->sell_price = (int)((double)total_cost * 1.217);
        dest->energy_value = total_cost / 0x1Cu;
        strncpy(dest->name, s1->title, 0x18u);
        if ( g_foodListHead_205060 )
        {
          for ( last = g_foodListHead_205060; last->next_cooked_food != g_foodListHead_205060; last = last->next_cooked_food )
            ;
          last->next_cooked_food = dest;
          dest->next_cooked_food = g_foodListHead_205060;
          dest->prev_cooked_food = last;
          g_foodListHead_205060->prev_cooked_food = dest;
        }
        else
        {
          g_foodListHead_205060 = dest;
          dest->next_cooked_food = dest;
          dest->prev_cooked_food = dest;
        }
        puts("Done !");
        return __readfsqword(0x28u) ^ v9;
      }
    }
  }
  return __readfsqword(0x28u) ^ v9;
}

//----- (00000000000025E1) ----------------------------------------------------
int fn_cooked_food_list_print_25E1()
{
  int g_foodListHead_205060; // eax
  int v1; // [rsp+4h] [rbp-Ch]
  CookedFood *cur; // [rsp+8h] [rbp-8h]

  v1 = 0;
  g_foodListHead_205060 = (int)g_foodListHead_205060;
  if ( g_foodListHead_205060 )
  {
    cur = g_foodListHead_205060;
    do
    {
      puts("*****************************************");
      _printf_chk(1, "No : %d\n");
      _printf_chk(1, "Name : %s\n");
      _printf_chk(1, "Price : %u\n");
      _printf_chk(1, "Energe : %lu\n");
      cur = cur->next_cooked_food;
      ++v1;
    }
    while ( cur != g_foodListHead_205060 );
    return puts("*****************************************");
  }
  return g_foodListHead_205060;
}

//----- (00000000000026C7) ----------------------------------------------------
__int64 fn_menu_shop_26C7()
{
  puts("@@@@@@@@@@@@@@@@@@@@@@@@@");
  puts("     Ingredient Shop     ");
  puts("@@@@@@@@@@@@@@@@@@@@@@@@@");
  puts("  1. Buy                 ");
  puts("  2. Sell                ");
  puts("  3. Make                ");
  puts("  4. Return              ");
  puts("@@@@@@@@@@@@@@@@@@@@@@@@@");
  return _printf_chk(1, "Your choice: ");
}

//----- (0000000000002744) ----------------------------------------------------
int fn_sell_2744()
{
  int g_foodListHead_205060; // eax
  int count; // [rsp+0h] [rbp-20h]
  int idx; // [rsp+4h] [rbp-1Ch]
  CookedFood *ptr_node; // [rsp+8h] [rbp-18h]
  struct CookedFood *prev; // [rsp+10h] [rbp-10h]
  CookedFood *next; // [rsp+18h] [rbp-8h]

  count = 0;
  fn_cooked_food_list_print_25E1();
  g_foodListHead_205060 = (int)g_foodListHead_205060;
  if ( g_foodListHead_205060 )
  {
    _printf_chk(1, "What do you want to sell ? :");
    idx = fn_read_number_1134();
    ptr_node = g_foodListHead_205060;
    while ( count != idx )
    {
      ptr_node = ptr_node->next_cooked_food;
      ++count;
      if ( ptr_node == g_foodListHead_205060 )
        return fn_printf_msg_11C0("Can not find the food !", 0);
    }
    g_playerMoney_2050C0 += ptr_node->sell_price;
    prev = ptr_node->prev_cooked_food;
    next = ptr_node->next_cooked_food;
    prev->next_cooked_food = next;
    next->prev_cooked_food = prev;
    realloc(ptr_node, 0);
    if ( ptr_node == g_foodListHead_205060 )
    {
      if ( g_foodListHead_205060 == next )
        g_foodListHead_205060 = 0;
      else
        g_foodListHead_205060 = next;
    }
    return puts("Success !");
  }
  return g_foodListHead_205060;
}

//----- (0000000000002895) ----------------------------------------------------
struct Ingredient *fn_make_2895()
{
  struct Ingredient *g_pantrySlots_2050C8; // rax
  int free_slot; // [rsp+4h] [rbp-Ch]
  Ingredient *ing_tmp; // [rsp+8h] [rbp-8h]

  if ( g_playerMoney_2050C0 <= 0x64 )
    return (struct Ingredient *)fn_printf_msg_11C0("You have no enough money :(\n", 0);
  g_playerMoney_2050C0 -= 100LL;
  g_pantrySlots_2050C8 = ::g_pantrySlots_2050C8;
  if ( ::g_pantrySlots_2050C8 )
  {
    for ( free_slot = 0; ; ++free_slot )
    {
      if ( free_slot > 9 )
        return (struct Ingredient *)fn_printf_msg_11C0("Too many ingredient", 0);
      if ( !*(_QWORD *)&::g_pantrySlots_2050C8->name[8 * free_slot] )
        break;
    }
    ing_tmp = (Ingredient *)realloc(0, 0x28u);
    if ( !ing_tmp )
      fn_printf_msg_11C0("Allocate failed !", 1);
    puts("NPC : I think you can make your ingredient by yourself");
    _printf_chk(1, "Ingredient :");
    puts("NPC : Enjoy it :)");
    memset(ing_tmp, 0, 0x20u);
    fn_read_string_11FF(ing_tmp->name, 0x1Fu);
    ing_tmp->price = rand() % 500;
    ing_tmp->quantity = 1;
    g_pantrySlots_2050C8 = ing_tmp;
    *(_QWORD *)&::g_pantrySlots_2050C8->name[8 * free_slot] = ing_tmp;
  }
  return g_pantrySlots_2050C8;
}

//----- (0000000000002A12) ----------------------------------------------------
int fn_eat_2A12()
{
  int g_foodListHead_205060; // eax
  int number_1134_1; // [rsp+0h] [rbp-20h]
  int number_1134; // [rsp+4h] [rbp-1Ch]
  CookedFood *ptr_node; // [rsp+8h] [rbp-18h]
  struct CookedFood *prev; // [rsp+10h] [rbp-10h]
  CookedFood *next; // [rsp+18h] [rbp-8h]

  number_1134_1 = 0;
  fn_cooked_food_list_print_25E1();
  g_foodListHead_205060 = (int)g_foodListHead_205060;
  if ( g_foodListHead_205060 )
  {
    _printf_chk(1, "What do you want to eat ? :");
    number_1134 = fn_read_number_1134();
    ptr_node = g_foodListHead_205060;
    while ( number_1134_1 != number_1134 )
    {
      ptr_node = ptr_node->next_cooked_food;
      ++number_1134_1;
      if ( ptr_node == g_foodListHead_205060 )
        return fn_printf_msg_11C0("Can not find the food !", 0);
    }
    g_playerPower_2050B8 += ptr_node->energy_value;
    prev = ptr_node->prev_cooked_food;
    next = ptr_node->next_cooked_food;
    prev->next_cooked_food = next;
    next->prev_cooked_food = prev;
    realloc(ptr_node, 0);
    if ( ptr_node == g_foodListHead_205060 )
    {
      if ( g_foodListHead_205060 == next )
        g_foodListHead_205060 = 0;
      else
        g_foodListHead_205060 = next;
    }
    return puts("Success !");
  }
  return g_foodListHead_205060;
}

//----- (0000000000002B62) ----------------------------------------------------
int fn_assignment_2B62()
{
  unsigned int i_tmp; // [rsp+Ch] [rbp-34h]
  unsigned int i; // [rsp+10h] [rbp-30h]
  unsigned int i_1; // [rsp+14h] [rbp-2Ch]
  Recipe *it; // [rsp+18h] [rbp-28h]
  Recipe *chosen; // [rsp+18h] [rbp-28h]
  CookedFood *ptr_node; // [rsp+20h] [rbp-20h]
  struct CookedFood *prev; // [rsp+30h] [rbp-10h]
  CookedFood *next; // [rsp+38h] [rbp-8h]

  i_tmp = 0;
  if ( !g_recipeListHead_2050D0 )
    return puts("NPC: I am very hungry !");
  for ( it = g_recipeListHead_2050D0; it; it = it->next_recipe )
    ++i_tmp;
  i_1 = rand() % i_tmp;
  chosen = g_recipeListHead_2050D0;
  for ( i = 0; i < i_1; ++i )
    chosen = chosen->next_recipe;
  _printf_chk(1, "NPC: I want to eat %s \nCan you prepare it for me ? \n");
  _printf_chk(1, "Your choice (1/Yes,0/No) :");
  if ( fn_read_number_1134() != 1 || !g_foodListHead_205060 )
    return puts("NPC: So sad :(");
  ptr_node = g_foodListHead_205060;
  while ( strcmp(ptr_node->name, chosen->title) )
  {
    ptr_node = ptr_node->next_cooked_food;
    ++i;
    if ( ptr_node == g_foodListHead_205060 )
      return fn_printf_msg_11C0("Can not find the food !", 0);
  }
  if ( g_playerXPBar_2050B0 + 80 <= 0x63 )
  {
    g_playerXPBar_2050B0 += 80LL;
  }
  else
  {
    ++g_playerLevel_2050A8;
    g_playerXPBar_2050B0 -= 20LL;
  }
  g_playerMoney_2050C0 += 434LL;
  prev = ptr_node->prev_cooked_food;
  next = ptr_node->next_cooked_food;
  prev->next_cooked_food = next;
  next->prev_cooked_food = prev;
  if ( ptr_node == g_foodListHead_205060 )
  {
    if ( g_foodListHead_205060 == next )
      g_foodListHead_205060 = 0;
    else
      g_foodListHead_205060 = next;
  }
  realloc(ptr_node, 0);                         // free
  return puts("NPC: Thank you !");
}

//----- (0000000000002DCA) ----------------------------------------------------
struct Ingredient *fn_shop_list_and_autorestock_2DCA()
{
  struct Ingredient *g_shopSlots_205080; // rax
  int i; // [rsp+4h] [rbp-Ch]
  unsigned int v2; // [rsp+8h] [rbp-8h]
  unsigned int n0xE; // [rsp+Ch] [rbp-4h]

  v2 = 0;
  g_shopSlots_205080 = g_shopSlots_205080;
  if ( g_shopSlots_205080 )
  {
    n0xE = time(0) - g_shopRestockEpoch_205068;
    if ( n0xE > 0xE )
      v2 = n0xE / 0xF;
    puts("#######################################################");
    for ( i = 0; i <= 9; ++i )
    {
      if ( *(_QWORD *)&g_shopSlots_205080->name[8 * i] )
      {
        *(_DWORD *)(*(_QWORD *)&g_shopSlots_205080->name[8 * i] + 36LL) += v2;
        _printf_chk(1, "No.%d\n  Ingredient : %s\n  Quantity : %u\n  Price : %u\n");
      }
    }
    puts("#######################################################");
    return (struct Ingredient *)_printf_chk(1, "What do you want to buy ? :");
  }
  return g_shopSlots_205080;
}

//----- (0000000000002F40) ----------------------------------------------------
int fn_buy_2F40()
{
  unsigned int idx; // [rsp+4h] [rbp-Ch]
  uint32_t qty; // [rsp+8h] [rbp-8h]
  unsigned int cost; // [rsp+Ch] [rbp-4h]

  fn_shop_list_and_autorestock_2DCA();
  idx = fn_read_number_1134();
  if ( idx > 9 )
    return fn_printf_msg_11C0("Out of bound\n", 11);
  if ( !*(_QWORD *)&g_shopSlots_205080->name[8 * idx] )
    return fn_printf_msg_11C0("Not found !", 0);
  _printf_chk(1, "Quantity :");
  qty = fn_read_number_1134();
  if ( *(_DWORD *)(*(_QWORD *)&g_shopSlots_205080->name[8 * idx] + 36LL) < qty )
    return puts("You can not buy so much !");
  cost = qty * *(_DWORD *)(*(_QWORD *)&g_shopSlots_205080->name[8 * idx] + 32LL);
  if ( g_playerMoney_2050C0 < cost )
    return puts("You do not have enough money :(");
  g_playerMoney_2050C0 -= cost;
  fn_pantry_add_or_update_ingredient_1276(
    *(const char **)&g_shopSlots_205080->name[8 * idx],
    qty,
    *(_DWORD *)(*(_QWORD *)&g_shopSlots_205080->name[8 * idx] + 32LL));
  *(_DWORD *)(*(_QWORD *)&g_shopSlots_205080->name[8 * idx] + 36LL) -= qty;
  return puts("Success !");
}

//----- (00000000000030E3) ----------------------------------------------------
unsigned __int64 fn_shop_30E3()
{
  unsigned __int64 n2; // rax

  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          fn_menu_shop_26C7();
          n2 = fn_read_number_1134();
          if ( n2 != 2 )
            break;
          fn_sell_2744();
        }
        if ( n2 > 2 )
          break;
        if ( n2 != 1 )
          goto LABEL_12;
        fn_buy_2F40();
      }
      if ( n2 != 3 )
        break;
      if ( (unsigned int)g_playerLevel_2050A8 > 3 )
        fn_make_2895();
    }
    if ( n2 == 4 )
      return n2;
LABEL_12:
    puts("Invalid Choice");
  }
}

//----- (000000000000316C) ----------------------------------------------------
_BYTE *fn_player_init_profile_316C()
{
  _BYTE *result; // rax

  _printf_chk(1, "Your name: ");
  result = (_BYTE *)fn_read_string_11FF(g_playerName_2050A0, 7);
  g_playerLevel_2050A8 = 1;
  g_playerXPBar_2050B0 = 0;
  g_playerPower_2050B8 = 20;
  g_playerMoney_2050C0 = 100;
  return result;
}

//----- (00000000000031C5) ----------------------------------------------------
void __fastcall __noreturn main(int a1, char **a2, char **a3)
{
  fn_game_init_FFC();
  fn_install_seccomp_filter_F00();
  fn_init_default_player_pantry_and_recipes_1E95();
  fn_player_init_profile_316C();
  fn_shop_init_inventory_2149();
  while ( 1 )
  {
    fn_main_menu_print_1DF4();
    switch ( fn_read_number_1134() )
    {
      case 1LL:
        fn_recipe_1CA9();
        break;
      case 2LL:
        fn_assignment_2B62();
        break;
      case 3LL:
        fn_chef_info_1D5A();
        break;
      case 4LL:
        fn_shop_30E3();
        break;
      case 5LL:
        fn_cook_2259();
        break;
      case 6LL:
        fn_eat_2A12();
        break;
      case 7LL:
        if ( g_flagFile_205058 )
          fclose(g_flagFile_205058);
        exit(0);
      default:
        continue;
    }
  }
}

//----- (00000000000032BA) ----------------------------------------------------
__int64 __fastcall fn_patch_seccomp_labels_32BA(_BYTE *buf, _BYTE *p_g_dataSeccomp_36E0, unsigned __int64 n0x19)
{
  int n0xFFFF; // eax
  unsigned __int64 i; // [rsp+28h] [rbp-18h]
  _BYTE *v6; // [rsp+38h] [rbp-8h]

  if ( !n0x19 || n0x19 > 0x1000 )
    return 0xFFFFFFFFLL;
  for ( i = 0; i < n0x19; ++i )
  {
    v6 = &p_g_dataSeccomp_36E0[8 * (n0x19 - i) - 8];
    if ( *(_WORD *)v6 == 5 )
    {
      n0xFFFF = ((unsigned __int8)v6[2] << 8) | (unsigned __int8)v6[3];
      if ( n0xFFFF == 65278 )
      {
        if ( *(_DWORD *)&buf[16 * *((unsigned int *)v6 + 1) + 16] != -1 )
        {
          fprintf(stderr, "Duplicate label use: '%s'\n", *(const char **)&buf[16 * *((unsigned int *)v6 + 1) + 8]);
          return 1;
        }
        *(_DWORD *)&buf[16 * *((unsigned int *)v6 + 1) + 16] = n0x19 - i - 1;
        *((_DWORD *)v6 + 1) = 0;
        v6[2] = 0;
        v6[3] = 0;
      }
      else if ( n0xFFFF == 0xFFFF )
      {
        if ( *(_DWORD *)&buf[16 * *((unsigned int *)v6 + 1) + 16] == -1 )
        {
          fprintf(stderr, "Unresolved label: '%s'\n", *(const char **)&buf[16 * *((unsigned int *)v6 + 1) + 8]);
          return 1;
        }
        *((_DWORD *)v6 + 1) = *(_DWORD *)&buf[16 * *((unsigned int *)v6 + 1) + 16] - (n0x19 - i);
        v6[2] = 0;
        v6[3] = 0;
      }
    }
  }
  return 0;
}

//----- (00000000000034B3) ----------------------------------------------------
__int64 __fastcall fn_get_or_add_label_index_34B3(int *a1, const char *s1)
{
  unsigned int v3; // [rsp+1Ch] [rbp-14h]
  int *v4; // [rsp+20h] [rbp-10h]
  int *v5; // [rsp+28h] [rbp-8h]

  v4 = a1 + 2;
  if ( *a1 == 256 )
  {
    fwrite("Too many labels\n", 1u, 0x10u, stderr);
    exit(1);
  }
  if ( *a1 )
  {
    v5 = &v4[4 * *a1];
    v3 = 0;
    while ( v4 < v5 )
    {
      if ( !strcmp(s1, *(const char **)v4) )
        return v3;
      v4 += 4;
      ++v3;
    }
    *(_QWORD *)v4 = s1;
    v4[2] = -1;
    ++*a1;
    return v3;
  }
  else
  {
    *(_QWORD *)v4 = s1;
    a1[4] = -1;
    ++*a1;
    return 0;
  }
}

//----- (00000000000035BB) ----------------------------------------------------
unsigned __int16 *__fastcall fn_sock_filter_35BB(unsigned __int16 *i_1, __int64 a2)
{
  unsigned __int16 *i_2; // rax
  unsigned __int16 *i; // [rsp+8h] [rbp-18h]

  for ( i = i_1; ; i += 4 )
  {
    i_2 = i;
    if ( i >= &i_1[4 * a2] )
      break;
    printf(
      "{ code=%u,jt=%u,jf=%u,k=%u },\n",
      *i,
      *((unsigned __int8 *)i + 2),
      *((unsigned __int8 *)i + 3),
      *((_DWORD *)i + 1));
  }
  return i_2;
}

//----- (0000000000003640) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 i_1; // rbp
  __int64 i; // rbx

  i_1 = &off_204CF8 - off_204CF0;
  init_proc();
  if ( i_1 )
  {
    for ( i = 0; i != i_1; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))off_204CF0[i])(a1, a2, a3);
  }
}
// 204CF0: using guessed type __int64 (__fastcall *off_204CF0[2])();
// 204CF8: using guessed type __int64 (__fastcall *off_204CF8)();

//----- (00000000000036B4) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=108 queued=42 decompiled=42 lumina nreq=0 worse=0 better=0
// ALL OK, 42 function(s) have been successfully decompiled
